### ISSUE TITLE
Updating readme for Unifi OS 1.6.x builds and up?

### ISSUE THREAD

**Issue by ethansawicki** [pbrah/wpa_supplicant-udmpro#1]
Not entirely sure how to just ask a question but as of UDMP firmware 1.6.3 they switched the os to Unifi OS and it uses podman instead of docker. Also there isn't anymore json support and this will not survive a reboot due to podman unless someone can figure out a way to automate "podman container start wpa_supplicant-udmpro" on boot.

**Comment by pbrah** [comment]
Sorry for the delay, I've updated the README.md.  Please let me know if this works for you.
