### ISSUE TITLE
docker container in exited state after udmp restart

### ISSUE THREAD

**Issue by ryanburnette** [pbrah/wpa_supplicant-udmpro#12]
My docker container ends up in an exited state after udmp restart

```
48c3432074d2  docker.io/pbrah/wpa_supplicant-udmpro:v1.0  -Dwired -ieth8 -c...  8 minutes ago  Exited (0) 3 minutes ago         wpa_supplicant-udmpro
```

Restarting fixes it

```
docker container restart [container id]
```

But I'd love to have it reconnect unattended

**Comment by boostchicken** [comment]
UDMP doesn't restart docker containers on reboot,  you need this the on_boot script below.

https://github.com/boostchicken/udm-utilities/
