### ISSUE TITLE
UXG-Pro doesn't have Docker/Podman installed, how to run? 

### ISSUE THREAD

**Issue by wjhanna** [pbrah/wpa_supplicant-udmpro#15]
I just got one of the early access UXG-Pro gateways and it doesn't have Docker or Podman on it. I assumed it was the same backend ad the UDM but I guess not.

I don't really know much about docker or this process, is this something that can be unpackaged and run outside of a docker container? Or does anyone know of a way to install docker on these new machines?

**Comment by wjhanna** [comment]
I posted this on the Ubiquiti forums and was told this will not work on the UXG-Pro due to how it's set up at the OS level: The UDM/P uses containers for the appliance, controller, etc, which is why it has that functionality baked in. The UXG-Pro is bare metal and doesn't need it as its intended to be a gateway only.

**Comment by alloylab** [comment]
just run wpa_supplicant on the bare metal device

**Comment by cinderblock** [comment]
@alloylab have you (or anyone) seen a good guide for this?

**Comment by ethansawicki** [comment]
Well since I think 0.5.5 they added podman to the uxg for the web setup. Still shows on mine on 1.9.0
