### ISSUE TITLE
Major/minor error

### ISSUE THREAD

**Issue by vcao** [pbrah/wpa_supplicant-udmpro#5]
I understand this was built on previous firmwares. I'm starting to get errors with 1.7.0 firmware. I ran the podman command and received:
`"WARNING: The same type, major and minor should not be used for multiple devices."`

Any updates or help troubleshooting would be greatly appreciated.

**Comment by GiulianoM** [comment]
It's a warning, not an error...

Related, from 2019:

https://github.com/containers/libpod/issues/3200

If you run "podman ps -a" does it show the wpa_supplicant-udmpro container?

Is the container running?

Start the container by running "podman start wpa_supplicant-udmpro".

Check the container to see if there are any errors, run "podman logs wpa_supplicant-udmpro".

**Comment by vcao** [comment]
I have the image, but can't start the container because of the error. I start with the following:

```
podman run --privileged --network=host --name=wpa_supplicant-udmpro -v /mnt/data/docker/wpa_supplicant/:/etc/wpa_supplicant/conf/ --log-driver=json-file --restart unless-stopped -d -ti pbrah/wpa_supplicant-udmpro:v1.0 -Dwired -ieth8 -c/etc/wpa_supplicant/conf/wpa_supplicant.conf
```

And the following errors are displayed:
```
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
Error: the unless-stopped restart policy is not supported: invalid argument
```
If it's the `--restart policy` then, I'll try removing it or switching it to always.

**Comment by vcao** [comment]
I was able to launch the container using ```--restart always``` instead of ```-restart unless-stopped```. The major/minor warnings persist. That being said, the restart policy does not work as provided and the issue should be left open. I had another user on reddit chime in to say that the issue is with the outdated version of podman that is provided on the UDM/UDMpro.

**Comment by pbrah** [comment]
Ubiquiti is missing something specifically to allow the restart to take place.  It has been a while since I've looked at this and I no longer own a UDM Pro however the only way for this to work is by an update provided by Ubiquiti or someone having an ability to write to their read only squashfs.   If I remember correctly there is some daemon we need to start with the UDM Pro that is not set to start.

**Comment by GiulianoM** [comment]
Actually, boostchicken found a way around the problem and created an on-boot script that starts the wpa_supplicant container.

https://github.com/boostchicken/udm-utilities

It works great!
